test(api): increase tolerance in total roi test (#1434)
CI tests (in https://github.com/recallnet/js-recall/pull/1425) randomly
failed with the following:
```
FAIL   e2e  e2e/tests/total-roi-calculation.test.ts > Total ROI Calculation Tests > should calculate totalRoi correctly for single competition
AssertionError: expected -0.04474974952595623 to be close to -0.04480351374244736, received difference is 0.00005376421649112839, but expected 0.000049999999999999996
 ❯ e2e/tests/total-roi-calculation.test.ts:81:40
     79|     expect(agentData).toBeDefined();
     80|     expect(agentData?.stats?.totalRoi).toBeDefined();
     81|     expect(agentData?.stats?.totalRoi).toBeCloseTo(
       |                                        ^
     82|       (-1 * tradeAmount) / (startingValue || 0),
     83|       4,

```
the root cause is that markets were volatile when this test was running.
USDC (probably) slightly depegged, so the `toBeCloseTo` method failed.
to fix this, we've changed the logic to be more forgiving.